### ISSUE TITLE
Cgl and CoinUtils are not updated

### ISSUE THREAD

**Issue by ycollet** [coin-or/CoinMP#16]
Cgl and CoinMP directories are not updated wrt the master repos of Cgl and CoinMP.

**Comment by tkralphs** [comment]
They are as far as I can see. E.g.,
- https://github.com/coin-or/CoinMP/commits/master
- https://projects.coin-or.org/CoinMP/log/

What is out of sync?

**Comment by ycollet** [comment]
In fact, I was talking about the svn repo on the coinor website.
Stefan explains me this situation is normal because coinor has swtiched to git, but I don't understand why some svn repo are in sync with git and not others repo.
I switched all my repos to git now.

**Comment by svigerske** [comment]
Some projects (e.g., Ipopt) moved completely to GitHub, some other live on subversion, but have their repository automatically mirrored to GitHub and also have their issue tracking on GitHub, and some others are still on subversion/trac only.
So using the git repo if it exists should give you the latest versions.
The trac page of a project usually redirects to the Github for projects that have both svn and github.

**Comment by ycollet** [comment]
Thanks for this info !

YC

**Comment by tkralphs** [comment]
Nevertheless, nothing should be out of sync except for maybe a few minutes here and there. The syncing happens every 10 minutes. I still don't really see what was out of sync. The log https://projects.coin-or.org/CoinMP/log/ _is_ for the SVN repo on the COIN-OR Web site.
